version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: customer_analysis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: customer_analysis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password_2024
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - customer_analysis_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: customer_analysis_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@customeranalysis.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password_2024
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./database/pgadmin-servers.json:/pgadmin4/servers.json
    networks:
      - customer_analysis_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  customer_analysis_network:
    driver: bridge