version: '3.8'

services:
  # Next.js Application - connects to external PostgreSQL
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer_analysis_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - customer_analysis_network

networks:
  customer_analysis_network:
    driver: bridge